name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-go-version:
    name: Get Go Version
    runs-on: ubuntu-latest
    outputs:
      go_version: ${{ steps.vars.outputs.go_version }}
    steps:
      - uses: actions/checkout@v6
      - name: Get Go version
        id: vars
        run: |
          goVersion=$(grep '^FROM golang' .github/go/Dockerfile | cut -d ':' -f 2 | cut -d '-' -f 1)
          echo "go_version=${goVersion}" >> $GITHUB_OUTPUT
          echo "Using Go version ${goVersion}"

  build:
    name: Build
    needs: get-go-version
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ needs.get-go-version.outputs.go_version }}
          cache: true
      - run: go mod download
      - name: Build
        run: go build ./...
        env:
          GOOS: ${{ matrix.os == 'ubuntu-latest' && 'linux' || (matrix.os == 'macos-latest' && 'darwin' || 'windows') }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
